#ifndef APP_CONFIG_H_INCLUDED
#define APP_CONFIG_H_INCLUDED

/*
 *  Macro riguardanti la configurazione dell'applicazione
 */

#define APP_CONFIG_FIRMWARE_VERSION_MAJOR 0UL
#define APP_CONFIG_FIRMWARE_VERSION_MINOR 1UL
#define APP_CONFIG_FIRMWARE_VERSION_PATCH 0UL

#define APP_CONFIG_TASK_SIZE 512

#define APP_CONFIG_PASSWORD "72346"

#define APP_CONFIG_MIN_PRESSURE_SETPOINT_DECIBAR 10
#define APP_CONFIG_MAX_PRESSURE_SETPOINT_DECIBAR 50

#define APP_CONFIG_DEFAULT_PID_KP 0.5
#define APP_CONFIG_DEFAULT_PID_KI 0.1
#define APP_CONFIG_DEFAULT_PID_KD 0.0

#endif
